// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaZmzH4RQcJ2au_QomNXlSuVsYRrbbV2s',
    appId: '1:88482312561:web:456d9835f224a4c51586d0',
    messagingSenderId: '88482312561',
    projectId: 'second-demo-f3d15',
    authDomain: 'second-demo-f3d15.firebaseapp.com',
    storageBucket: 'second-demo-f3d15.appspot.com',
    measurementId: 'G-Y6RBXRF101',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChn5pUS2itewU9XlMuHz8kP4njUGmD_Kk',
    appId: '1:88482312561:android:66dd37b067b857f91586d0',
    messagingSenderId: '88482312561',
    projectId: 'second-demo-f3d15',
    storageBucket: 'second-demo-f3d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dHRQdijaxwuFxVEm5u-22jPfggYYkic',
    appId: '1:88482312561:ios:cbe680f18d860e261586d0',
    messagingSenderId: '88482312561',
    projectId: 'second-demo-f3d15',
    storageBucket: 'second-demo-f3d15.appspot.com',
    iosBundleId: 'com.example.flutterApplication111Copy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4dHRQdijaxwuFxVEm5u-22jPfggYYkic',
    appId: '1:88482312561:ios:9f66833ec2ccf6401586d0',
    messagingSenderId: '88482312561',
    projectId: 'second-demo-f3d15',
    storageBucket: 'second-demo-f3d15.appspot.com',
    iosBundleId: 'com.example.flutterApplication111Copy.RunnerTests',
  );
}
